{% set name = "pyCHX" %}
{% set version = "4.1.0" %}
{% set sha256 = "2760514ef23f1c1a4b02b5d9e17d5fb5fc2f77021c9b423e7ff4b54bd5c2e7e5" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: {{ sha256 }}

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps

requirements:
  host:
    - python >=3.6,!=3.9.5,!=3.8.10
    - pip
  run:
    - python >=3.6,!=3.9.5,!=3.8.10
    - cython
    - dask
    - databroker
    - dill
    - ipython
    - lmfit
    - matplotlib
    - numpy
    - pandas
    - pillow
    - pyyaml
    - reportlab
    - scipy
    - theano
    - tifffile
    - tqdm
    - xray-vision

test:
  imports:
    - pyCHX
    - pyCHX.v2
    - pyCHX.v2._commonspeckle
    - pyCHX.v2._futurepyCHX

about:
  home: https://github.com/NSLS-II/pyCHX
  license: BSD-3-Clause
  license_family: BSD
  license_file: LICENSE
  summary: pyCHX - NSLS-II CHX XPCS Data Analysis Package
